package:
  name: reportbot
  version: 0.0.1

source:
  git_url: https://github.com/susieluckyball/reportbot.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

build:
  entry_points: 
    - report_run = reportbot.cli:report_run 
  script: $PYTHON $RECIPE_DIR/setup.py install