package:
  name: reportbot
  version: 0.0.1

source:
  path: ./

requirements:
  build:
    - python
    - setuptools
  run:
    - python

build:
  entry_point: 
    - report_run = reportbot.cli.report_run 
  script: python setup.py install